image: nixos/nix:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-env -iA nixpkgs.stack
- nix-env -iA nixpkgs.hlint

stages:
- build

hlint:
  stage: lint
  script:
  - hlint .

build:
  stage: build
  script:
  - stack --nix build --ghc-options "-Wall -Werror"
