name:                within
version:             0.1.0.1
license:             MIT
git:                 https://gitlab.com/homotopic-tech/within
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"
category:            Filesystem

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A value within another path.
description:         Simple newtype for representing a value within a well-typed directory. Useful for when you need to jump between directories and change filenames independently. Uses the path library.

dependencies:
- base >= 4.7 && < 5
- comonad
- free
- exceptions
- hashable
- path

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
